### ISSUE TITLE
Add DCR to the surface operations list

### ISSUE THREAD

**Issue by cwwalter** [lsst/sims_GalSimInterface#53]
When using the atmospheric PSF (or in all cases?) we should add DCR to the list of surface operations.  @rmjarvis can you comment on any issues to be aware of?

**Comment by rmjarvis** [comment]
Sorry.  Should have commented here.  [Cross-reference](https://github.com/LSSTDESC/imSim/issues/100#issuecomment-391144210)

**Comment by danielsf** [comment]
Is there something I can read to get up to speed on what is meant by "surface operations"?  I started seeing that term being used about six months ago.  I assume it is a GalSim term of art.  Thanks.

**Comment by rmjarvis** [comment]
Yes, it is a term of art.  Basically, they are functions that act on the photon array in between where they are shot (rendering the surface brightness profile at the surface of the silicon) and accumulated in the sensor.

We've been using them to 
- give wavelengths to the photons based on an SED (so not chromatic shooting, but chromatic after that)
- give photons non-normal incidence angles based on the f-ratio and obscuration
- apply chromatic dcr shifts to the positions of photons

It also provides a hook for not-yet-implemented effects, such as
- fringing
- surface layer reflection
- possibly vignetting

There's unfortunately not great documentation of them currently.  Our docs (as everyone's) still needs some work. And this is one area where the [doc strings](https://github.com/GalSim-developers/GalSim/blob/releases/1.6/galsim/photon_array.py#L271) probably aren't sufficient to get a good feel for how to use them.  Perhaps the photon array [test suite](https://github.com/GalSim-developers/GalSim/blob/releases/1.6/tests/test_photon_array.py) would be a place to look for semi-real-world usage.

**Comment by cwwalter** [comment]
This was done a long time ago..
